#!/bin/bash
set -eou pipefail

## Enable this hook with: git config
## git config core.hooksPath .git-hooks/

. scripts/common.sh

validate_compile () {
	log_it >&2
	npm run build
}

validate_other () {
	log_it >&2
	if grep 'set -eou'; then
		log_error "found 'set -eou'!  Change to 'set -euo pipefail'."
		exit 1
	fi
}

validate_version () {
	log_it >&2
	VER1=$(jq '.version' < package.json)
	VER2=$(jq '.version' < package-lock.json)
	if [ "$VER1" != "$VER2" ]; then
		log_error "version does not match between package.json and package-lock.json! ($VER1 != $VER2)"
		exit 1
	fi
}

########## MAIN BLOCK ##########
validate_compile
validate_other
validate_version
log_it 'pre-commit checks successful!' >&2
