name: Publish Release

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    steps:
      - name: echo "GITHUB_REF_TYPE=$GITHUB_REF_TYPE GITHUB_HEAD_REF=$GITHUB_HEAD_REF GITHUB_REF_NAME=$GITHUB_REF_NAME" && exit 1
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          npm run package
          gh release upload "$GITHUB_HEAD_REF" bats-test-runner-*.vsix
          npm run deploy
