name: "🐛 Bug Report"
description: File a bug report
title: "🐛 [Bug]  <title here>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out this bug report!**  Your contribution helps this extension continue to be useful to the community.  Issues are triaged on a regular basis, but please be patient as we work through the backlog.  Pull requests are always welcome if you'd like to tackle the issue yourself.
  # - type: dropdown
  #   id: version
  #   attributes:
  #     label: BATS Version
  #     options:
  #       - '0.0'
  #       - 'other (please specify in the description)'
  #   validations:
  #     required: true
  - type: textarea
    attributes:
      label: Bug Description
      value: |
        Describe the bug...
    validations:
      required: true
