name: "🙋‍♀️ Question"
description: Ask a question
title: "🙋‍♀️ [Question] <title here>"
labels: ["question"]
# projects: ["octo-org/1", "octo-org/44"]
assignees:
  - kherring
body:
  - type: markdown
    attributes:
      value: |
        Ask a question, and please be sure to provide as much context as is necessary.
  # - type: dropdown
  #   id: version
  #   attributes:
  #     label: BATS Version
  #     options:
  #       - '0.0'
  #       - 'other (please specify in the description)'
  #   validations:
  #     required: true
  - type: textarea
    attributes:
      label: Question
      value: |
        Ask your question here...
    validations:
      required: true
